### ISSUE TITLE
record file deletion time for later purge

### ISSUE THREAD

**Issue by shoki** [firespring/mogbak#16]
it would be useful to just record the timestamp when a file gets deleted from mogilefs. Mogbak could than provide a purge command with an parameter for the retention period of deleted files. 

Such a function provisions accidental deletion of files in mogilefs.

**Comment by jasonwilk** [comment]
We are archiving this project. We are closing all issues as unresolved. If anybody would like to address this issue, feel free to fork the project and implement the change. 

Thank you!
